Feat/form
kacper-echaust/panini-creator pull request #3
Opened 2024-12-11 07:08 UTC by kacper-echaust

2024-12-11 07:09 UTC, NerdbordMentor commented on declaration.d.ts
> +declare module '*.module.css' {
**suggestion**: Consider adding a comment explaining the purpose of declaring these modules, as it can help other developers understand why they are needed.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/App.css
> +@import url('https://fonts.googleapis.com/css2?family=Oxygen+Mono&display=swap');
**nitpick**: Consider organizing your font imports alphabetically for better readability.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Carousel/Carousel.module.css
> +	width: 250px;
**suggestion**: Consider using relative units like percentages or ems for width to make the component more responsive.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Carousel/Carousel.tsx
> +	const [value, setValue] = useState(0)
**suggestion**: Consider using a more descriptive name for the state variable 'value' to indicate what it represents.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Checkbox/Checkbox.tsx
> +			<input className={`${css.input} ${className}`} type='checkbox' id={name} />
**suggestion**: Consider adding an 'aria-label' to the input for better accessibility.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Form.module.css
> +	opacity: 0;
**suggestion**: Consider using CSS variables for colors and font sizes to maintain consistency and ease future changes.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Form.tsx
> +		<form className={`${css.form} ${animate ? css.fadeIn : ''}`}>
**praise**: Great job using CSS modules to scope styles locally and avoid conflicts.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Section/Section.module.css
> +.title{
**nitpick**: Ensure consistent spacing between CSS properties for better readability.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Select/Select.tsx
> +	const [value, setValue] = useState(data[0])
**suggestion**: Consider initializing the 'value' state with a more meaningful default, if applicable.

2024-12-11 07:09 UTC, NerdbordMentor commented on src/Components/Form/Switch/Switch.tsx
> +	const [isOn, setIsOn] = useState(true)
**suggestion**: Consider initializing 'isOn' with a prop to make the component more flexible.

2024-12-11 07:09 UTC, NerdbordMentor requested changes
The code changes introduce a comprehensive set of components and styles that align with the task requirements. The new components such as Carousel, Checkbox, Select, and Switch are well-structured and utilize mock data as required. The Form component has been updated to include these new sections, and the CSS modules are appropriately used to style the components according to the design specifications. The use of TypeScript for type safety and the modular approach to CSS are commendable.

### Things Missing: 

- [] The task requires a "Configure Base" form section screen based on the provided design. While the code includes a form with various sections, it is not explicitly clear if the "Configure Base" section is implemented exactly as per the design. A review of the design against the implementation is necessary to ensure full compliance.

### Things That Went Well:

- The modularization of components and CSS is well-executed, making the codebase maintainable and scalable.
- The use of TypeScript enhances type safety and reduces potential runtime errors.
- The components are designed to be reusable and are integrated well into the Form component.
- The mock data usage aligns with the task requirements, ensuring that the components can be tested without backend dependencies.

2024-12-12 11:19 UTC, Sumick approved these changes
Mostly looks good - Im leaving tips regarding future development and some cleanup related comments

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Carousel/Carousel.tsx
> +	const [value, setValue] = useState(0)
**nit:** I would set enum as value here, because currently its not meaningful. Nerdy is right. eg: `enum CarouselValues `

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Form.tsx
> +						{vegetableVariant.map((item, index) => {
**nit:** looks like prettier is missing formatting

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Form.tsx
> +									<input type='checkbox' id={item} />
**nit:** This should be separate component

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Form.tsx
> +					<Switch id='egg'>
**nit:** comment to remove?

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Select/Select.tsx
> +								key={index}
**nit:** looks this is missing formatting as well

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Switch/Switch.tsx
> +	const [arrayComponents, setArrayComponents] = useState<ReactNode[]>([children])
**nit:** instead of components, you should keep array of objects, because you won't be able to access data easily later when managing form state

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Switch/Switch.tsx
> +					arrayComponents.map(component => {
**nit:** There is no formatting here

2024-12-12 11:19 UTC, Sumick commented on src/Components/Form/Switch/Switch.tsx
> +							handleDelete(id)
**nit:** This will work now, but it won't work later when you will have to integrate values with form state. Try to refactor it now to objects, as it will be easier later

2024-12-15 12:19 UTC, kacper-echaust commented on src/Components/Form/Form.tsx
> +					<Switch id='egg'>
I did a little too much and only later saw that each section was divided into a separate task in the nerdbord

2024-12-16 15:22 UTC, merged